gpu_id: '0'
log_wandb: False

# lrurec settings
hidden_size: 64                 # (int) Number of features in the hidden state.
n_layers: 2                  # (int) Number of Mamba layers.
dropout_prob: 0.2            # (float) Dropout rate.
loss_type: 'CE'                 # (str) Type of loss function. Range in ['BPR', 'CE'].


## dataset settings
# dataset: ml-1m
# MAX_ITEM_LIST_LENGTH: 200       # 200 for MovieLens-1M

dataset: amazon-clothing
#dataset: kuairand
# dataset: steam
MAX_ITEM_LIST_LENGTH: 50      # 50 for Amazon datasets

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
load_col:
   inter: [user_id, item_id, timestamp]

# USER_ID_FIELD: user_id
# ITEM_ID_FIELD: product_id
# load_col:
#     inter: [user_id, product_id, timestamp]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# training settings
epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10
train_neg_sample_args: ~
train_from_scratch: False

# evaluation settings
weight_decay: 0.0
metrics: ['Hit', 'NDCG', 'MRR', 'Precision', 'Recall', 'MAP']
valid_metric: NDCG@10
eval_batch_size: 4096
topk: [5,10,20]

seed: 42
