name: base
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=22.11.1=py310h06a4308_4
  - conda-content-trust=0.1.3=py310h06a4308_0
  - conda-package-handling=1.9.0=py310h5eee18b_1
  - cryptography=38.0.1=py310h9ce1e76_0
  - idna=3.4=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - pycosat=0.6.4=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.8=h7a1cb2a_1
  - readline=8.2=h5eee18b_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - setuptools=65.5.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py310h06a4308_0
  - tqdm=4.64.1=py310h06a4308_0
  - urllib3=1.26.13=py310h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - aiosignal==1.4.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - automat==25.4.16
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - buildtools==1.0.6
      - causal-conv1d==1.4.0
      - click==8.2.1
      - colorama==0.4.4
      - colorlog==4.7.2
      - comm==0.2.2
      - constantly==23.10.4
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distlib==0.4.0
      - docopt==0.6.2
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.14.0
      - fonttools==4.53.0
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2024.6.0
      - furl==2.1.4
      - greenlet==3.2.4
      - grpcio==1.64.1
      - h11==0.14.0
      - hf-xet==1.1.9
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.34.4
      - hyperlink==21.0.0
      - incremental==24.7.2
      - ipykernel==6.29.4
      - ipython==8.25.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.5.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.2
      - jupyterlab-language-pack-zh-cn==4.2.post1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - kmeans-pytorch==0.3
      - lightgbm==4.6.0
      - mamba-ssm==2.2.2
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.1
      - narwhals==2.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.13.0
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-nccl-cu12==2.28.3
      - openpyxl==3.1.5
      - orderedmultidict==1.0.1
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.3.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.2
      - plotly==6.3.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytorch-fast-transformers==0.4.0
      - pytz==2025.2
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - ray==2.3.0
      - recbole==1.2.0
      - redo==3.0.0
      - referencing==0.35.1
      - regex==2025.9.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - simplejson==3.20.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.43
      - stack-data==0.6.3
      - supervisor==4.2.5
      - sympy==1.12.1
      - tabulate==0.9.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - texttable==1.7.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tinycss2==1.3.0
      - tokenizers==0.15.2
      - tomli==2.0.1
      - torch==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - tornado==6.4.1
      - traitlets==5.14.3
      - transformers==4.37.0
      - triton==2.1.0
      - twisted==25.5.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - virtualenv==20.34.0
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - xgboost==3.0.5
      - zope-interface==7.2
prefix: /root/miniconda3
